<a href="https://colab.research.google.com/github/VidhyaMadhavi/EIP3/blob/master/Session2_lstm_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
## Shared_link :  https://colab.research.google.com/drive/1zwz7wUNlpm1QpqShyco8C8de4mUdFnie

## SESSION 2 - Assignment  - LSTM- RNN


Go through this Post: https://machinelearningmastery.com/text-generation-lstm-recurrent-neural-networks-python-keras/
 (Links to an external site.)
 
  Add these improvements to the final code described in the post: 
  - Predict 500 characters only
  -  Remove all the punctuation from the source text
  - Train the model on padded sequences
   (Links to an external site.)
   rather than random sequences of characters. 
  - Train the model for 100 epochs
  -  Add dropout to the input layer, remove it from the layer before dense layer. Use Dropout value of 0.1 everywhere
  - Submit!

## Approach Followed:

- Removed the punctuation from the source
- Divided the sentences with \n
- Find the unique characters and point them to numbers
- Converted the sentences in to mapping numbers
- Pad all the sentences
- Prepare the train data - for every sentence the last characer is the output
- Applied dropout in the input layer
- Train the model for 100 epochs
- Predict 500 characters  by passing 500 sentences

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/EIP3.0')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.callbacks import ModelCheckpoint
from keras.utils import np_utils

In [0]:
# load ascii text and covert to lowercase
filename = "wonderland.txt"
raw_text = open(filename).read()
raw_text = raw_text.lower()

In [50]:
print(type(raw_text))
print(len(raw_text))

<class 'str'>
144407


In [0]:
# print(raw_text)

## Removing punctuation from the source

In [51]:
from string import punctuation
print("The following are the punctuation :", punctuation)

print("Removing the Punctuation and the displaying the result data")
def strip_punctuation(s):
    return ''.join(c for c in s if c not in punctuation )

raw_text = strip_punctuation(raw_text)

The following are the punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
Removing the Punctuation and the displaying the result data


In [0]:
# print(raw_text)

In [52]:
list_of_sentences = raw_text.split("\n")
print(len (list_of_sentences))
# print(len (list_of_sentences), list_of_sentences)

3337


In [53]:
list_of_sentences_updated = []
for i in list_of_sentences:
  if len(i)> 0:
    list_of_sentences_updated.append(i)
print(len (list_of_sentences_updated))
# print(len (list_of_sentences_updated), list_of_sentences_updated)

2480


## Now convert these sentences in to sequence of number and prepare the training data

In [18]:
sorted(list (set (' '.join(list_of_sentences_updated))))

[' ',
 '0',
 '3',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [20]:
# create mapping of unique chars to integers

chars = sorted(list (set (' '.join(list_of_sentences_updated))))
char_to_int = dict((c, i) for i, c in enumerate(chars))
print(char_to_int)

{' ': 0, '0': 1, '3': 2, 'a': 3, 'b': 4, 'c': 5, 'd': 6, 'e': 7, 'f': 8, 'g': 9, 'h': 10, 'i': 11, 'j': 12, 'k': 13, 'l': 14, 'm': 15, 'n': 16, 'o': 17, 'p': 18, 'q': 19, 'r': 20, 's': 21, 't': 22, 'u': 23, 'v': 24, 'w': 25, 'x': 26, 'y': 27, 'z': 28}


In [21]:
n_chars = len(raw_text)
n_vocab = len(chars)
print ("Total Characters: ", n_chars)
print ("Total Vocab: ", n_vocab)

Total Characters:  136087
Total Vocab:  29


### Convert the text of sentences in to numbers

In [0]:
#find the length of each sentence
list_of_sentences_updated_numbers = []
for sentence in list_of_sentences_updated:
#   print(len(sentence))
  char_to_listofnumbers = [char_to_int[char] for char in sentence]
  list_of_sentences_updated_numbers.append (char_to_listofnumbers )

## Creating padded sequences for list_of_sentences_updated

In [23]:
from keras.preprocessing.sequence import pad_sequences
# define sequences
sequences = list_of_sentences_updated_numbers
# pad sequence
padded = pad_sequences(sequences)
print(padded)

[[ 0  0  0 ...  3 16  6]
 [ 0  0  0 ... 17 14 14]
 [ 0  0  0 ...  0  2  1]
 ...
 [ 0  0  0 ... 11 22 10]
 [ 0  0  0 ... 17 27 21]
 [ 0  0  0 ...  3 27 21]]


In [45]:
for i in padded[0:50]:
  print(len(i) , i [-1])

73 6
73 14
73 1
73 7
73 7
73 7
73 16
73 20
73 21
73 7
73 7
73 6
73 16
73 20
73 17
73 20
73 22
73 7
73 10
73 16
73 6
73 10
73 6
73 7
73 7
73 25
73 16
73 16
73 13
73 18
73 14
73 6
73 21
73 22
73 7
73 10
73 21
73 21
73 22
73 20
73 21
73 22
73 14
73 22
73 18
73 7
73 25
73 9
73 20
73 14


In [25]:
# prepare the dataset of input to output pairs encoded as integers
dataX = []
dataY = []

for sentence in padded:
  train_input = sentence[0: -1]
  train_output = sentence[-1] 
  dataX.append(train_input)
  dataY.append(train_output)
n_patterns = len(dataX)
print ("Total Patterns: ", n_patterns)

Total Patterns:  2480


In [26]:
print(len(dataX),len(dataY) )
print (len(dataX[0]), dataX[0], dataY[0] )
print(len(dataX[1]), dataX[1], dataY[1])

2480 2480
72 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 14 11  5  7 21
  0  3  6 24  7 16 22 23 20  7 21  0 11 16  0 25 17 16  6  7 20 14  3 16] 6
72 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 14  7 25 11 21  0  5  3 20 20 17 14] 14


In [0]:
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (n_patterns, len(dataX[0]), 1))
# normalize
X = X / float(n_vocab)
# one hot encode the output variable
y = np_utils.to_categorical(dataY)

### Add dropout to the input layer and remove dropout  before Dense

In [28]:
model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2]), return_sequences=True, dropout = 0.1))
model.add(Dropout(0.1))
model.add(LSTM(256))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')

W0725 14:57:57.995127 139697040070528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0725 14:57:58.046234 139697040070528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0725 14:57:58.054367 139697040070528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0725 14:57:58.250471 139697040070528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0725 14:57:58.261350 

In [29]:
# define the checkpoint
filepath="2_weights-improvement-{epoch:02d}-{loss:.4f}-bigger.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]
# fit the model
model.fit(X, y, epochs=100, batch_size=64, callbacks=callbacks_list)

W0725 14:58:27.972914 139697040070528 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/100
2480/2480 [==============================] - 12s 5ms/step - loss: 2.6994

Epoch 00001: loss improved from inf to 2.69941, saving model to 2_weights-improvement-01-2.6994-bigger.hdf5
Epoch 2/100
2480/2480 [==============================] - 8s 3ms/step - loss: 2.5756

Epoch 00002: loss improved from 2.69941 to 2.57557, saving model to 2_weights-improvement-02-2.5756-bigger.hdf5
Epoch 3/100
2480/2480 [==============================] - 8s 3ms/step - loss: 2.5788

Epoch 00003: loss did not improve from 2.57557
Epoch 4/100
2480/2480 [==============================] - 8s 3ms/step - loss: 2.5705

Epoch 00004: loss improved from 2.57557 to 2.57047, saving model to 2_weights-improvement-04-2.5705-bigger.hdf5
Epoch 5/100
2480/2480 [==============================] - 8s 3ms/step - loss: 2.5750

Epoch 00005: loss did not improve from 2.57047
Epoch 6/100
2480/2480 [==============================] - 8s 3ms/step - loss: 2.5643

Epoch 00006: loss improved from 2.57047 to 2.56431, saving mode

In [0]:
# load the network weights
filename = "2_weights-improvement-98-0.2013-bigger.hdf5"
model.load_weights(filename)
model.compile(loss='categorical_crossentropy', optimizer='adam')

In [32]:
int_to_char = dict((i, c) for i, c in enumerate(chars))
int_to_char

{0: ' ',
 1: '0',
 2: '3',
 3: 'a',
 4: 'b',
 5: 'c',
 6: 'd',
 7: 'e',
 8: 'f',
 9: 'g',
 10: 'h',
 11: 'i',
 12: 'j',
 13: 'k',
 14: 'l',
 15: 'm',
 16: 'n',
 17: 'o',
 18: 'p',
 19: 'q',
 20: 'r',
 21: 's',
 22: 't',
 23: 'u',
 24: 'v',
 25: 'w',
 26: 'x',
 27: 'y',
 28: 'z'}

In [41]:
import sys
# pick a random seed
start = numpy.random.randint(0, len(dataX)-1)
pattern = list(dataX[start])
print ("Seed:",start )
print ("\"", ''.join([int_to_char[value] for value in pattern]), "\"")
# generate characters
for i in range(500):
	x = numpy.reshape(pattern, (1, len(pattern), 1))
	x = x / float(n_vocab)
	prediction = model.predict(x, verbose=0)
	index = numpy.argmax(prediction)
	result = int_to_char[index]
# 	seq_in = [int_to_char[value] for value in pattern]
	print(result, end = '')
	pattern.append(index)
	pattern = pattern[1:len(pattern)]
print ("\nDone.")

Seed: 1768
"       as they walked off together alice heard the king say in a low voic "
esestytestesryyyyesnesryyyyesneskyyyyssnnngddaatdssssessyyessedrdatouressgsyyyedrnngddaatdsserngrnyyesneseaaaannngeddiredtedmysyhsnerndinryyesnesesytyysessyydsnyyyyedrrdaatosessesssyedredtssndssnyesyyyedrrwddrowmdssurdssyyedrrwtessyyysessyyyyessnyyyyyesneskyyyyynsnngddysyyessgsyyyysnnngddddtsssesscrryyyyessesyyyyyesnngdrdatesysmsneddaatsreddmdrdrtttessesryyyyedrnggrsyyynsndsnyyyyesneskyyyyynsnngddystyessestyyyssnnngddaatxttessedrsyyymsnnngyyyyysesnyyyyesneskyyyyyessgyyyyysesngddtttyytesngsgdddys
Done.


In [42]:
import sys
# pick a random seed
start = numpy.random.randint(0, len(dataX)-1)
pattern = list(dataX[start])
print ("Seed:",start )
print ("\"", ''.join([int_to_char[value] for value in pattern]), "\"")
# generate characters
for i in range(500):
	x = numpy.reshape(pattern, (1, len(pattern), 1))
	x = x / float(n_vocab)
	prediction = model.predict(x, verbose=0)
	index = numpy.argmax(prediction)
	result = int_to_char[index]
# 	seq_in = [int_to_char[value] for value in pattern]
	print(result, end = '')
	pattern.append(index)
	pattern = pattern[1:len(pattern)]
print ("\nDone.")

Seed: 2125
"                                                               was talkin "
gdddssernesesnernesndsnnndsnnresnnddreanysndddnnedaaodensssessnyyyyyyyessuuynsnesgdrytyysesngsyyyyyessnyndddatttessgsyyyessesrytdstgdrsyyyssnnngddaatdssssessyyessedrdatourdssgsryyedrnngddaatssdssessnyyyyndsngskyyyyesneskyyyyynsnngddystyessesryyyssnnngddaatxttesserryyyyessgsyyyyyessnynyyyesngskdrytyysesnngddaattrdddmttteddtttyyyesfdsstyyyesseskyyyyyessgsyyyysesngskyyyynsnngdddtsttessgsyyyysesngstyyyynsnnngdddtsttessgdrsyyesnnsgsgdrtuyessnsndddaatxtdddtttteddtttyyyyyessyyypesgdrstyysesngskddddtttm
Done.


In [43]:
import sys
# pick a random seed
start = numpy.random.randint(0, len(dataX)-1)
pattern = list(dataX[start])
print ("Seed:",start )
print ("\"", ''.join([int_to_char[value] for value in pattern]), "\"")
# generate characters
for i in range(500):
	x = numpy.reshape(pattern, (1, len(pattern), 1))
	x = x / float(n_vocab)
	prediction = model.predict(x, verbose=0)
	index = numpy.argmax(prediction)
	result = int_to_char[index]
# 	seq_in = [int_to_char[value] for value in pattern]
	print(result, end = '')
	pattern.append(index)
	pattern = pattern[1:len(pattern)]
print ("\nDone.")

Seed: 1244
"    conversation dropped and the party sat silent for a minute while alic "
esesyyyssssyyyyyyyyyyyyyyndsnddaatttterseyyyyeddatotgdddtdstttessgryyyyyesneskyyyyesnessyyypdsngsgdrstndstgsyyyedrrngddaatstdrsesedrdsynsndsstyysessnyyyyyesngskyyyyyessgyyyyysesnngdddttttessgsyyyysnnngddaatxttesserryyyyessesyyyyyessnyyyyyesngskygdrfyyutessnnngdddttttessnyyyessesryyyynsnngddaatdrsssessyyeddaatotgdddttttesseryyyyyyyyyyyyyndddatneeysyyessedrsyyesneskyyyyynsndsnyyyyessesyyyysnnngdddtsttessgstyyyedrnddaatotessersedrsyypsndsngtyyyessesryyyyessnyyyyyesngskyyyyynsnngddystyysessgyyyyysnn
Done.
